name: Validate

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Setup cmake
      uses: jwlawson/actions-setup-cmake@v1.9
      with:
        cmake-version: '3.16.x'
    - name: Setup ninja
      uses: seanmiddleditch/gha-setup-ninja@master
    - name: Set up GCC
      uses: egor-tensin/setup-gcc@v1
      with:
        version: latest
        platform: x64
    - uses: actions/checkout@v2
    - name: Make build directory
      working-directory: ${{github.workspace}}/cpp
      run: |
          mkdir build   
    - name: Build with cmake
      working-directory: ${{github.workspace}}/cpp/build
      run: |
           cmake ${{github.workspace}}/cpp -DCMAKE_GENERATOR:INTERNAL=Ninja
           make
    - name: Run Tests
      working-directory: ${{github.workspace}}/cpp/build
      run: |
           pwd
           ls
           ./unittests
