name: Validate

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Setup cmake
      uses: jwlawson/actions-setup-cmake@v1.9
      with:
        cmake-version: '3.16.x'
    - name: Set up GCC
      uses: egor-tensin/setup-gcc@v1
      with:
        version: latest
        platform: x64
    - name: cd to cpp
      run: pwd
    - name: cd to cpp
      run: cd ./cpp
    - name: Make build directory
      run: mkdir build
    - name: cd tp build directory
      run: cd build  
    - name: Use cmake
      run: cmake ../
    - name: Run Tests
      run: cd ../
    - name: Run executable
      run: ./tests/impl_tests
