name: Validate

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Setup cmake
      uses: jwlawson/actions-setup-cmake@v1.9
      with:
        cmake-version: '3.16.x'
    - name: Set up GCC
      uses: egor-tensin/setup-gcc@v1
      with:
        version: latest
        platform: x64
    - uses: actions/checkout@v2
    - name: Make build directory
      run: |
          mkdir build
          cd build   
    - name: Use cmake
      run: cmake ../cpp
    - name: Run Tests
      run: |
           ./tests/impl_tests
